// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBz48DP3ZaX6oX4TnTfZfeladPX73b0orE',
    appId: '1:500161903549:android:c2f45f29fa0d0a8a8a30d4',
    messagingSenderId: '500161903549',
    projectId: 'pintopia-2025',
    storageBucket: 'pintopia-2025.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeZ1a2F9LZL5B93m4UqGdw92jaW3Sv-GA',
    appId: '1:500161903549:ios:c350151b1a7ce6e68a30d4',
    messagingSenderId: '500161903549',
    projectId: 'pintopia-2025',
    storageBucket: 'pintopia-2025.firebasestorage.app',
    iosBundleId: 'org.pintopia.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfbhRKTd_2V5szemQrdDV2crQstJZWNDg',
    appId: '1:500161903549:web:98b097807715c5538a30d4',
    messagingSenderId: '500161903549',
    projectId: 'pintopia-2025',
    authDomain: 'pintopia-2025.firebaseapp.com',
    storageBucket: 'pintopia-2025.firebasestorage.app',
    measurementId: 'G-2VB5G1YS2T',
  );

}